# Generated by Django 5.1.5 on 2025-03-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="활동명")),
                (
                    "thumbnail",
                    models.ImageField(upload_to="imgages/", verbose_name="썸네일 이미지"),
                ),
                ("content", models.TextField(verbose_name="내용")),
            ],
            options={
                "verbose_name": "활동 갤러리",
                "verbose_name_plural": "활동 갤러리",
            },
        ),
        migrations.CreateModel(
            name="ActivityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="태그"),
                ),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "태그 관리",
            },
        ),
        migrations.CreateModel(
            name="ActionPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="activity_photos/")),
                (
                    "activity_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="activity_gallery.activityaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_tags",
                        to="activity_gallery.activityaction",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_relations",
                        to="activity_gallery.activitytag",
                    ),
                ),
            ],
            options={
                "unique_together": {("activity_action", "tag")},
            },
        ),
        migrations.AddField(
            model_name="activityaction",
            name="tags",
            field=models.ManyToManyField(
                related_name="actions",
                through="activity_gallery.ActivityTagRelation",
                to="activity_gallery.activitytag",
            ),
        ),
    ]
