# Generated by Django 5.1.5 on 2025-03-01 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity_gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityaction",
            options={
                "verbose_name": "활동 갤러리",
                "verbose_name_plural": "활동 갤러리",
            },
        ),
    ]
