# Generated by Django 5.1.5 on 2025-03-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity_gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitytag",
            options={"verbose_name": "태그", "verbose_name_plural": "활동 태그 관리"},
        ),
    ]
