# Generated by Django 5.1.5 on 2025-03-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_gallery", "0002_alter_activityaction_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityaction",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="imgages/",
                verbose_name="썸네일 이미지",
            ),
        ),
    ]
