# Generated by Django 5.1.5 on 2025-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_gallery", "0003_activityaction_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityaction",
            name="thumbnail",
            field=models.ImageField(upload_to="imgages/", verbose_name="썸네일 이미지"),
        ),
    ]
