# Generated by Django 5.1.5 on 2025-03-18 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity_gallery", "0004_alter_activityaction_thumbnail"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activitytag",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="activitytag",
            name="activity_action",
        ),
        migrations.RemoveField(
            model_name="activitytag",
            name="tag",
        ),
    ]
