# Generated by Django 5.1.5 on 2025-03-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_gallery", "0005_alter_activitytag_unique_together_and_more"),
        ("public", "0003_alter_tag_options_alter_tag_name_activitytag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityaction",
            name="tags",
            field=models.ManyToManyField(
                related_name="actions", through="public.ActivityTag", to="public.tag"
            ),
        ),
        migrations.DeleteModel(
            name="ActivityTag",
        ),
    ]
