# Generated by Django 5.1.5 on 2025-03-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_gallery", "0006_alter_activityaction_tags_delete_activitytag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionphoto",
            name="image",
            field=models.ImageField(upload_to="activity/action-photo/"),
        ),
        migrations.AlterField(
            model_name="activityaction",
            name="thumbnail",
            field=models.ImageField(upload_to="activity/thumbnail/", verbose_name="썸네일 이미지"),
        ),
    ]
