# Generated by Django 5.1.5 on 2025-06-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_gallery", "0007_alter_actionphoto_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="숨김 여부")),
                ("title", models.CharField(max_length=255, verbose_name="활동명")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activity/history/thumbnail/",
                        verbose_name="활동 썸네일 이미지",
                    ),
                ),
                ("activity_date", models.DateField(verbose_name="활동 날짜")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "활동 히스토리",
                "verbose_name_plural": "활동 히스토리",
                "ordering": ("activity_date",),
            },
        ),
    ]
