# Generated by Django 5.2.3 on 2025-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_gallery", "0008_activityhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityaction",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="숨김 여부"),
        ),
        migrations.AddField(
            model_name="activityaction",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="활동 공개 여부"),
        ),
        migrations.AddField(
            model_name="activityhistory",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="히스토리 공개 여부"),
        ),
        migrations.AlterField(
            model_name="actionphoto",
            name="image",
            field=models.ImageField(upload_to="activity/action-photo/", verbose_name="활동 사진"),
        ),
        migrations.AlterField(
            model_name="activityaction",
            name="content",
            field=models.TextField(verbose_name="커뮤니티 활동 내용"),
        ),
        migrations.AlterField(
            model_name="activityhistory",
            name="content",
            field=models.TextField(verbose_name="히스토리 내용"),
        ),
        migrations.AlterField(
            model_name="activityhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
        ),
        migrations.AlterField(
            model_name="activityhistory",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="activity/history/thumbnail/",
                verbose_name="히스토리 썸네일",
            ),
        ),
        migrations.AlterField(
            model_name="activityhistory",
            name="title",
            field=models.CharField(max_length=255, verbose_name="히스토리 이름"),
        ),
        migrations.AlterField(
            model_name="activityhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
    ]
