openapi: 3.0.3
info:
  title: HelloPy Backend API
  version: 0.1.0
paths:
  /api/faqs/:
    get:
      operationId: faqs_retrieve
      description: 모든 FAQ 목록 조회
      tags:
      - faqs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        200/성공:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSuccessResponse'
          description: ''
        200/에러:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ''
  /api/faqs/{id}/:
    get:
      operationId: faqs_retrieve_2
      description: 모든 FAQ 목록 조회
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this FAQ.
        required: true
      tags:
      - faqs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        200/성공:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
          description: 응답 성공
        200/에러:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 응답 에러
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - code
      - message
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          default: ERROR
        error:
          $ref: '#/components/schemas/Error'
      required:
      - error
    ListSuccessResponse:
      type: object
      properties:
        status:
          type: string
          default: SUCCESS
        data:
          type: array
          items:
            type: object
            additionalProperties: {}
        pagination:
          allOf:
          - $ref: '#/components/schemas/PageNumberPagination'
          nullable: true
    PageNumberPagination:
      type: object
      properties:
        count:
          type: integer
        next:
          type: string
        previous:
          type: string
      required:
      - count
      - next
      - previous
    SuccessResponse:
      type: object
      properties:
        status:
          type: string
          default: SUCCESS
        data:
          type: object
          additionalProperties: {}
        pagination:
          allOf:
          - $ref: '#/components/schemas/PageNumberPagination'
          nullable: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
