openapi: 3.0.3
info:
  title: HelloPy Backend API
  version: 0.1.0
paths:
  /api/faqs/:
    get:
      operationId: faqs_list
      description: 모든 FAQ 목록 조회
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      tags:
      - faqs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses: {}
  /api/faqs/{id}/:
    get:
      operationId: faqs_retrieve
      description: '## 특정 FAQ 조회'
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this FAQ.
        required: true
      tags:
      - faqs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FAQ'
          description: ''
components:
  schemas:
    FAQ:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        question:
          type: string
          title: 질문
          maxLength: 255
        answer:
          type: string
          title: 답변
        is_deleted:
          type: boolean
          title: 삭제 여부
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - answer
      - created_at
      - id
      - question
      - updated_at
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
