<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-25 18:42
=======
# Generated by Django 5.1.5 on 2025-02-24 12:32
>>>>>>> bb8cb6b (Feature/md (#50))

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Merchandise",
=======
            name="Md",
>>>>>>> bb8cb6b (Feature/md (#50))
            fields=[
                (
                    "id",
                    models.BigAutoField(
<<<<<<< HEAD
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="상품 이름")),
                ("description", models.TextField(blank=True, null=True, verbose_name="상품 설명")),
                ("image", models.ImageField(upload_to="images/", verbose_name="썸네일 이미지")),
=======
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/")),
>>>>>>> bb8cb6b (Feature/md (#50))
            ],
        ),
    ]
