# Generated by Django 5.1.5 on 2025-03-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchandise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchandise",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="썸네일 이미지"
            ),
        ),
    ]
