# Generated by Django 5.1.5 on 2025-03-20 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("merchandise", "0003_alter_merchandise_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchandise",
            options={
                "verbose_name": "MD 상품 관리",
                "verbose_name_plural": "MD 상품 관리",
            },
        ),
    ]
