# Generated by Django 5.1.5 on 2025-03-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchandise", "0004_alter_merchandise_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchandise",
            name="image",
            field=models.ImageField(upload_to="merchandise/image/", verbose_name="썸네일 이미지"),
        ),
    ]
