# Generated by Django 5.1.5 on 2025-03-16 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("merchandise", "0004_alter_merchandise_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchandise",
            options={"verbose_name": "MD 상품", "verbose_name_plural": "MD 상품"},
        ),
    ]
