# Generated by Django 5.2.3 on 2025-07-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchandise", "0005_alter_merchandise_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchandise",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="숨김 여부"),
        ),
        migrations.AddField(
            model_name="merchandise",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="상품 공개 여부"),
        ),
    ]
