# Generated by Django 5.1.5 on 2025-02-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="삭제 여부")),
                ("content", models.TextField(verbose_name="내용")),
                ("is_deleted", models.BooleanField(verbose_name="삭제 여부")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="고정 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "공지",
                "verbose_name_plural": "공지사항",
            },
        ),
    ]
