# Generated by Django 5.1.5 on 2025-03-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="태그"),
                ),
            ],
            options={
                "verbose_name": "태그",
                "verbose_name_plural": "공지사항 태그 관리",
            },
        ),
        migrations.CreateModel(
            name="NoticeTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_tags",
                        to="notice.notice",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_relations",
                        to="notice.noticetag",
                    ),
                ),
            ],
            options={
                "unique_together": {("notice", "tag")},
            },
        ),
        migrations.AddField(
            model_name="notice",
            name="tag",
            field=models.ManyToManyField(
                related_name="notices",
                through="notice.NoticeTagRelation",
                to="notice.noticetag",
            ),
        ),
    ]
