# Generated by Django 5.1.5 on 2025-03-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0002_alter_notice_options"),
        ("public", "0004_alter_activitytag_options_noticetag"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="tag",
            field=models.ManyToManyField(
                related_name="notice", through="public.NoticeTag", to="public.tag"
            ),
        ),
    ]
