# Generated by Django 5.1.5 on 2025-03-20 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0003_notice_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={"verbose_name": "공지사항", "verbose_name_plural": "공지사항"},
        ),
    ]
