# Generated by Django 5.1.5 on 2025-03-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0004_alter_notice_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항",
            },
        ),
        migrations.AlterField(
            model_name="notice",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="숨김 여부"),
        ),
    ]
