# Generated by Django 5.1.5 on 2025-03-24 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0005_alter_notice_options_alter_notice_is_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notice",
            old_name="tag",
            new_name="tags",
        ),
    ]
