# Generated by Django 5.2.3 on 2025-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0006_rename_tag_notice_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="공지사항 공개 여부"),
        ),
    ]
