# Generated by Django 5.1.5 on 2025-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagementInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="이름")),
                ("role", models.CharField(max_length=10, verbose_name="역할")),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
                ),
                (
                    "linkedin",
                    models.TextField(blank=True, null=True, verbose_name="LinkedIn 프로필 URL"),
                ),
                (
                    "github",
                    models.TextField(blank=True, null=True, verbose_name="Github 프로필 URL"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/", verbose_name="사진"
                    ),
                ),
            ],
        ),
    ]
