# Generated by Django 5.1.5 on 2025-02-28 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ManagementInfo",
            new_name="Manager",
        ),
    ]
