# Generated by Django 5.1.5 on 2025-02-28 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_rename_managementinfo_manager"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manager",
            options={"verbose_name": "운영진", "verbose_name_plural": "운영진"},
        ),
    ]
