# Generated by Django 5.1.5 on 2025-03-20 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_alter_manager_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manager",
            options={
                "verbose_name": "운영진 관리",
                "verbose_name_plural": "운영진 관리",
            },
        ),
    ]
