# Generated by Django 5.1.5 on 2025-03-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_alter_manager_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="manager/photo/", verbose_name="사진"
            ),
        ),
    ]
