# Generated by Django 5.1.5 on 2025-02-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("public", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="활동명")),
                ("content", models.TextField(verbose_name="내용")),
            ],
        ),
        migrations.CreateModel(
            name="ActionPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="community_photos/")),
                (
                    "community_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="community_action.communityaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "community_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_tags",
                        to="community_action.communityaction",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="public.tag"),
                ),
            ],
            options={
                "unique_together": {("community_action", "tag")},
            },
        ),
        migrations.AddField(
            model_name="communityaction",
            name="tags",
            field=models.ManyToManyField(
                related_name="actions",
                through="community_action.CommunityTag",
                to="public.tag",
            ),
        ),
    ]
