# Generated by Django 5.1.5 on 2025-03-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "공통 모듈", "verbose_name_plural": "태그 관리"},
        ),
    ]
