# Generated by Django 5.1.5 on 2025-03-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_gallery", "0005_alter_activitytag_unique_together_and_more"),
        ("public", "0002_alter_tag_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="태그"),
        ),
        migrations.CreateModel(
            name="ActivityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_tags",
                        to="activity_gallery.activityaction",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="public.tag"),
                ),
            ],
            options={
                "verbose_name": "활동 태그 릴레이션",
                "verbose_name_plural": "활동 태그 릴레이션",
                "unique_together": {("activity_action", "tag")},
            },
        ),
    ]
