# Generated by Django 5.1.5 on 2025-03-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0002_alter_notice_options"),
        ("public", "0003_alter_tag_options_alter_tag_name_activitytag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitytag",
            options={"verbose_name": "활동 태그", "verbose_name_plural": "활동 태그"},
        ),
        migrations.CreateModel(
            name="NoticeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notice_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_tags",
                        to="notice.notice",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="public.tag"),
                ),
            ],
            options={
                "verbose_name": "공지 태그",
                "verbose_name_plural": "공지 태그",
                "unique_together": {("notice_action", "tag")},
            },
        ),
    ]
