# Generated by Django 5.1.5 on 2025-03-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public", "0004_alter_activitytag_options_noticetag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="domain",
            field=models.CharField(
                choices=[
                    ("activity", "Activity"),
                    ("notice", "Notice"),
                    ("default", "Default"),
                ],
                default="default",
                max_length=10,
                verbose_name="도메인",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "domain")},
        ),
    ]
