# Generated by Django 5.1.5 on 2025-03-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0004_alter_notice_options"),
        ("public", "0006_alter_tag_options_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticetag",
            name="notice_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notice_tags",
                to="notice.notice",
            ),
        ),
    ]
