# Generated by Django 5.2.3 on 2025-07-05 14:30

import datetime

import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("public", "0007_alter_noticetag_notice_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="임시 저장된 이미지 경로")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="임시 저장 일시"),
                ),
                (
                    "expiry_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.TruncDate(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.functions.datetime.Now(),
                                "+",
                                models.Value(datetime.timedelta(days=1)),
                            ),
                            output_field=models.DateField(),
                        ),
                        verbose_name="만료 일시",
                    ),
                ),
            ],
            options={
                "verbose_name": "임시 이미지",
                "verbose_name_plural": "임시 이미지들",
                "indexes": [models.Index(fields=["path"], name="public_temp_path_a3ab43_idx")],
            },
        ),
    ]
