# Generated by Django 5.1.5 on 2025-02-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "게시됨"),
                            ("hidden", "숨김"),
                            ("deleted", "삭제됨"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="게시물 상태",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="질문")),
                ("answer", models.TextField(verbose_name="답변")),
                (
                    "question_type",
                    models.CharField(
                        choices=[("activity", "활동"), ("conference", "기타등등")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "게시됨"),
                            ("hidden", "숨김"),
                            ("deleted", "삭제됨"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="게시물 상태",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="공지 제목")),
                ("content", models.TextField(verbose_name="공지 내용")),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항 목록",
            },
        ),
    ]
