# Generated by Django 5.1.5 on 2025-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notice",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="question_type",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="status",
        ),
        migrations.AddField(
            model_name="faq",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
