# Generated by Django 5.1.5 on 2025-03-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0004_delete_notice_alter_faq_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="숨김 여부"),
        ),
    ]
