# Generated by Django 5.1.5 on 2025-03-05 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0005_alter_faq_is_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "자주하는 질문"},
        ),
    ]
