# Generated by Django 5.1.5 on 2025-03-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0006_alter_faq_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "자주하는 질문",
            },
        ),
    ]
