# Generated by Django 5.2.3 on 2025-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0007_alter_faq_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.AddField(
            model_name="faq",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="공개 여부"),
        ),
    ]
