# Generated by Django 5.1.5 on 2025-03-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PymonCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_month",
                    models.DateField(default="2024-01-01", verbose_name="연도-월"),
                ),
                (
                    "description",
                    models.CharField(default="파이몬 설명", max_length=100, verbose_name="설명"),
                ),
                ("calendar_photo", models.ImageField(upload_to="calendar/")),
            ],
            options={
                "verbose_name": "Calendar",
            },
        ),
    ]
