# Generated by Django 5.1.5 on 2025-03-20 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pymon_calendar", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pymoncalendar",
            options={
                "verbose_name": "캘린더 관리",
                "verbose_name_plural": "캘린더 관리",
            },
        ),
    ]
