# Generated by Django 5.1.5 on 2025-03-20 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pymon_calendar", "0002_alter_pymoncalendar_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pymoncalendar",
            options={
                "verbose_name": "이달의 달력",
                "verbose_name_plural": "이달의 달력",
            },
        ),
    ]
